package GUI;



import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import sushi.SushiBar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dingu
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    boolean[] seatTaken,waiting;
    final int NoOfSeats = 5;
    final int MaxWaiting = 7;
    final int sleepDuration = 1000;
    public mainForm() {
        initComponents();
        seatTaken = new boolean[NoOfSeats]; 
        waiting = new boolean[MaxWaiting];
       
        for(int i=0;i<NoOfSeats;i++)
        {
            seatPanel.getComponent(i).setVisible(false);
        }
        
        for(int i=0;i<MaxWaiting;i++)
        {
            waitingPanel.getComponent(i).setVisible(false);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waitingPanel = new javax.swing.JPanel();
        waiting1 = new javax.swing.JLabel();
        waiting2 = new javax.swing.JLabel();
        waiting3 = new javax.swing.JLabel();
        waiting4 = new javax.swing.JLabel();
        waiting5 = new javax.swing.JLabel();
        waiting6 = new javax.swing.JLabel();
        waiting7 = new javax.swing.JLabel();
        seatPanel = new javax.swing.JPanel();
        seat1 = new javax.swing.JLabel();
        seat2 = new javax.swing.JLabel();
        seat3 = new javax.swing.JLabel();
        seat4 = new javax.swing.JLabel();
        seat5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        waitingPanel.setBackground(new java.awt.Color(255, 255, 255));
        waitingPanel.setOpaque(false);

        waiting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting1.setText("1");

        waiting2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting2.setText("1");

        waiting3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting3.setText("1");

        waiting4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting4.setText("1");

        waiting5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting5.setText("1");

        waiting6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting6.setText("1");

        waiting7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting7.setText("1");

        javax.swing.GroupLayout waitingPanelLayout = new javax.swing.GroupLayout(waitingPanel);
        waitingPanel.setLayout(waitingPanelLayout);
        waitingPanelLayout.setHorizontalGroup(
            waitingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitingPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(waiting7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(waitingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waiting3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(waitingPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(waiting1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(waitingPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(waiting4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(waitingPanelLayout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(waiting5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(waiting6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(waitingPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(waiting2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        waitingPanelLayout.setVerticalGroup(
            waitingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(waiting7)
            .addComponent(waiting3)
            .addComponent(waiting1)
            .addComponent(waiting4)
            .addComponent(waiting5)
            .addComponent(waiting6)
            .addComponent(waiting2)
        );

        seatPanel.setBackground(new java.awt.Color(102, 0, 204));
        seatPanel.setOpaque(false);

        seat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat1.setText("1");

        seat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat2.setText("2");

        seat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat3.setText("3");

        seat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat4.setText("4");

        seat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat5.setText("5");

        javax.swing.GroupLayout seatPanelLayout = new javax.swing.GroupLayout(seatPanel);
        seatPanel.setLayout(seatPanelLayout);
        seatPanelLayout.setHorizontalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatPanelLayout.createSequentialGroup()
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(seat2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(seat1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(seat5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(seat4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(seatPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(seat3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        seatPanelLayout.setVerticalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seat2)
            .addComponent(seat1)
            .addComponent(seat5)
            .addComponent(seat4)
            .addComponent(seat3)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(waitingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(waitingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        mainForm form = new mainForm();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form.setVisible(true);
            }
        });
        
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
           SushiBar sushiBar = new SushiBar();
           sushiBar.startTheSushiBar(form);
        } catch (InterruptedException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel seat1;
    private javax.swing.JLabel seat2;
    private javax.swing.JLabel seat3;
    private javax.swing.JLabel seat4;
    private javax.swing.JLabel seat5;
    private javax.swing.JPanel seatPanel;
    private javax.swing.JLabel waiting1;
    private javax.swing.JLabel waiting2;
    private javax.swing.JLabel waiting3;
    private javax.swing.JLabel waiting4;
    private javax.swing.JLabel waiting5;
    private javax.swing.JLabel waiting6;
    private javax.swing.JLabel waiting7;
    private javax.swing.JPanel waitingPanel;
    // End of variables declaration//GEN-END:variables

    public void addCustomerToTable() throws InterruptedException {
         
        
      for(int i=0;i< NoOfSeats;i++)
      {
        if(!seatTaken[i])
        {
            seatTaken[i] = true;
             Thread.sleep(sleepDuration);
            seatPanel.getComponent(i).setVisible(true);
    
            return ;

        } 
      }
       
        

    }

    public void removeCustomerFromTable() {
        
      for(int i=0;i< NoOfSeats;i++)
      {
        if(seatTaken[i])
        {
            seatTaken[i] = false;
            seatPanel.getComponent(i).setVisible(false);
           
            return ;

        } 
      }
        
    }

    public void addPersonWaiting() throws InterruptedException {
        
      for(int i=0;i< MaxWaiting;i++)
      {
        if(!waiting[i])
        {
            waiting[i] = true;
             Thread.sleep(sleepDuration);
            waitingPanel.getComponent(i).setVisible(true);
            return ;

        } 
      }
    }

    public void removePersonWaiting() {
      for(int i=0;i< MaxWaiting;i++)
      {
        if(waiting[i])
        {
            waiting[i] = false;
            waitingPanel.getComponent(i).setVisible(false);
            return ;

        } 
      }
    }
}
