package GUI;



import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.audio.AudioData;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import sun.audio.ContinuousAudioDataStream;
import sushi.SushiBar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dingu
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    boolean[] seatTaken,waiting;
    final int NoOfSeats = 5;
    final int MaxWaiting = 7;
    final int sleepDuration = 1000;
    public mainForm() {
        initComponents();
        seatTaken = new boolean[NoOfSeats]; 
        waiting = new boolean[MaxWaiting];
       
        for(int i=0;i<NoOfSeats;i++)
        {
            seatPanel.getComponent(i).setVisible(false);
        }
        
        for(int i=0;i<MaxWaiting;i++)
        {
            waitingPanel.getComponent(i).setVisible(false);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waitingPanel = new javax.swing.JPanel();
        waiting1 = new javax.swing.JLabel();
        waiting2 = new javax.swing.JLabel();
        waiting3 = new javax.swing.JLabel();
        waiting4 = new javax.swing.JLabel();
        waiting5 = new javax.swing.JLabel();
        waiting6 = new javax.swing.JLabel();
        waiting7 = new javax.swing.JLabel();
        seatPanel = new javax.swing.JPanel();
        seat1 = new javax.swing.JLabel();
        seat2 = new javax.swing.JLabel();
        seat3 = new javax.swing.JLabel();
        seat4 = new javax.swing.JLabel();
        seat5 = new javax.swing.JLabel();
        dyningText = new javax.swing.JLabel();
        waitingText = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        waitingPanel.setBackground(new java.awt.Color(255, 255, 255));
        waitingPanel.setOpaque(false);

        waiting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting1.setText("1");

        waiting2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting2.setText("1");

        waiting3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting3.setText("1");

        waiting4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting4.setText("1");

        waiting5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting5.setText("1");

        waiting6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting6.setText("1");

        waiting7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/wait.jpg"))); // NOI18N
        waiting7.setText("1");

        javax.swing.GroupLayout waitingPanelLayout = new javax.swing.GroupLayout(waitingPanel);
        waitingPanel.setLayout(waitingPanelLayout);
        waitingPanelLayout.setHorizontalGroup(
            waitingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitingPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(waiting7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(waitingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waiting3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(waitingPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(waiting1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(waitingPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(waiting4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(waitingPanelLayout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(waiting5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(waiting6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(waitingPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(waiting2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        waitingPanelLayout.setVerticalGroup(
            waitingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(waiting7)
            .addComponent(waiting3)
            .addComponent(waiting1)
            .addComponent(waiting4)
            .addComponent(waiting5)
            .addComponent(waiting6)
            .addComponent(waiting2)
        );

        getContentPane().add(waitingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        seatPanel.setBackground(new java.awt.Color(102, 0, 204));
        seatPanel.setOpaque(false);

        seat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat1.setText("1");

        seat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat2.setText("2");

        seat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat3.setText("3");

        seat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat4.setText("4");

        seat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eating.gif"))); // NOI18N
        seat5.setText("5");

        javax.swing.GroupLayout seatPanelLayout = new javax.swing.GroupLayout(seatPanel);
        seatPanel.setLayout(seatPanelLayout);
        seatPanelLayout.setHorizontalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatPanelLayout.createSequentialGroup()
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(seat2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(seat1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(seat5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(seat4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(seatPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(seat3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        seatPanelLayout.setVerticalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seat2)
            .addComponent(seat1)
            .addComponent(seat5)
            .addComponent(seat4)
            .addComponent(seat3)
        );

        getContentPane().add(seatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 160));

        dyningText.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dyningText.setForeground(new java.awt.Color(204, 204, 204));
        dyningText.setText("All Seats are free right now");
        getContentPane().add(dyningText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 650, 30));

        waitingText.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        waitingText.setForeground(new java.awt.Color(204, 204, 204));
        waitingText.setText("No one is waiting");
        getContentPane().add(waitingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/background.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      playaudio();   
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        mainForm form = new mainForm();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form.setVisible(true);
            }
        });
        
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
           SushiBar sushiBar = new SushiBar();
           sushiBar.startTheSushiBar(form);
        } catch (InterruptedException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel dyningText;
    private javax.swing.JLabel seat1;
    private javax.swing.JLabel seat2;
    private javax.swing.JLabel seat3;
    private javax.swing.JLabel seat4;
    private javax.swing.JLabel seat5;
    private javax.swing.JPanel seatPanel;
    private javax.swing.JLabel waiting1;
    private javax.swing.JLabel waiting2;
    private javax.swing.JLabel waiting3;
    private javax.swing.JLabel waiting4;
    private javax.swing.JLabel waiting5;
    private javax.swing.JLabel waiting6;
    private javax.swing.JLabel waiting7;
    private javax.swing.JPanel waitingPanel;
    private javax.swing.JLabel waitingText;
    // End of variables declaration//GEN-END:variables

    public void addCustomerToTable() throws InterruptedException {
         
        
      for(int i=0;i< NoOfSeats;i++)
      {
        if(!seatTaken[i])
        {
            seatTaken[i] = true;
             Thread.sleep(sleepDuration);
            seatPanel.getComponent(i).setVisible(true);
            int c = getNoOfPeopleDining();
            if(c == 1)
                dyningText.setText(c + " person is dining . " + (NoOfSeats -c) + " seats are free");
            else
                dyningText.setText(c + " people are dining together. " + (NoOfSeats -c) + " seats are free");
    
            return ;

        } 
      }
       
        

    }

    public void removeCustomerFromTable() {
        
      for(int i=0;i< NoOfSeats;i++)
      {
        if(seatTaken[i])
        {
            seatTaken[i] = false;
            seatPanel.getComponent(i).setVisible(false);
            dyningText.setText("");
           
            return ;

        } 
      }
        
    }

    public void addPersonWaiting() throws InterruptedException {
        
      for(int i=0;i< MaxWaiting;i++)
      {
        if(!waiting[i])
        {
            waiting[i] = true;
             Thread.sleep(sleepDuration);
            waitingPanel.getComponent(i).setVisible(true);
            int c  = getNoOfPeopleWaiting();
            if(c == 1)
                 waitingText.setText(c + " person is waiting outside.");
            else
                 waitingText.setText(c + " people are waiting outside.");
            return ;

        } 
      }
    }

    public void removePersonWaiting() {
      for(int i=0;i< MaxWaiting;i++)
      {
        if(waiting[i])
        {
            waiting[i] = false;
            waitingPanel.getComponent(i).setVisible(false);
            int c  = getNoOfPeopleWaiting();
            if(c == 1)
                 waitingText.setText(c + " person is waiting outside.");
            else
                 waitingText.setText(c + " people are waiting outside.");
            return ;

        } 
      }
    }
    
    public int getNoOfPeopleDining()
    {
        int c =0;
        for(int i=0;i< NoOfSeats;i++)
      {
        if(seatTaken[i])
        {
            c++;

        } 
      }
        
        return c;
    }
    
    public int getNoOfPeopleWaiting()
    {
        int c =0;
        for(int i=0;i< MaxWaiting;i++)
      {
        if(waiting[i])
        {
            c++;

        } 
      }
        
        return c;
    }

    private void playaudio() {
       
        try {
            
//        AudioPlayer MGP = AudioPlayer.player;
//        AudioStream BGM;
//        AudioData MD;
//        ContinuousAudioDataStream loop = null;
//        try{
//        BGM = new AudioStream((InputStream)new FileInputStream("/home/dingu/newBackground.mp3"));
//        MD = BGM.getData();
//        loop = new ContinuousAudioDataStream(MD);
//        }catch(IOException error){
//        System.out.print("file not found : " +error);
//        }
//        MGP.start(loop);


//        Clip clip = null;
//        try {
//            clip = AudioSystem.getClip();
//        } catch (LineUnavailableException ex) {
//            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        AudioInputStream inputStream = AudioSystem.getAudioInputStream(SoundManager.class.getResourceAsStream("C://temp/my.mp3"));
//        try {
//            clip.open(inputStream);
//        } catch (LineUnavailableException ex) {
//            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        clip.start(); 


File file = new File("/home/dingu/newBackground.wav");
AudioInputStream audioStream = null;
try {
    audioStream = AudioSystem.getAudioInputStream(file);
} catch (UnsupportedAudioFileException ex) {
    Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
} catch (IOException ex) {
    Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
}

AudioFormat format = audioStream.getFormat();
DataLine.Info info = new DataLine.Info(Clip.class, format);
Clip audioClip = (Clip) AudioSystem.getLine(info);

audioClip.open(audioStream);
audioClip.start();

        } catch (LineUnavailableException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
